imagePullSecret: ghcr-pull-secret

replicaCount: 3
image:
  repository: ghcr.io/gamal0909/cart-service
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 8082      
  targetPort: 8082

hpa:
  minReplicas: 3
  maxReplicas: 10
