apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
        - name: inventory-container
          image: ghcr.io/gamal0909/inventory-service:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8083
