apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secret.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword }}
  POSTGRES_DB: {{ .Values.secret.postgresDb }}
